### ISSUE TITLE
.idpass not setup? Variables file does not exist

### ISSUE THREAD

**Issue by dantam74** [hengsin/idempiere-dev-setup#11]
Hi!

This script works as a charm, except that it fails when any of the setups are tried to be run i eclipse. With setups I mean

install.silent.app
install.console.app
install.app

An execute call to /idempiere-dev-setup/idempiere/org.adempiere.server-feature/utils.unix/getVar.sh
from 
org.compiere.install.ConfigurationData.load fails to find the file .idpass

Adding the environment variable

-DIDEMPIERE_SECURE_PROPERTIES=false

to the debug/run configuration solves this problem, but it also means that .idpass is not setup from what I understand. 

https://groups.google.com/g/idempiere/c/fhug5803JQk/m/CMigpLKnAgAJ

If this problem didn't occur the setup script would work without any trouble :-) Final piece for a super handy setup.

**Comment by hengsin** [comment]
Just tested with current source from master and .idpass does get created after run of install.app from eclipse. Perhaps you are running with an user account that doesn't have the necessary write permission ?

**Comment by dantam74** [comment]
Forgot to say that I'm using the release branches (previous test was on release-9)
A fresh run of the script using 

./setup.sh --branch=release-10

Gives the same error as previously. All files and subdirectories are owned by the same user.

20:20:13.299 ConfigurationData.load: /home/daniel/github/idempiere-dev-setup/idempiere/idempiereEnv.properties [1]
org.adempiere.exceptions.AdempiereException: Could not execute /home/daniel/github/idempiere-dev-setup/idempiere/org.adempiere.server-feature/utils.unix/getVar.sh
	at org.compiere.util.Ini.runCommand(Ini.java:865)
	at org.compiere.util.Ini.getVar(Ini.java:808)
	at org.compiere.install.ConfigurationData.load(ConfigurationData.java:254)
	at org.compiere.install.ConfigurationPanel.dynInit(ConfigurationPanel.java:447)
	at org.compiere.install.Setup.<init>(Setup.java:77)
	at org.compiere.install.Setup.main(Setup.java:165)
	at org.compiere.install.InstallApplication.start(InstallApplication.java:32)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: java.lang.Exception: Variables file does not exist
	at org.compiere.util.Ini.runCommand(Ini.java:861)
	... 19 more

Adding the environment variable

-DIDEMPIERE_SECURE_PROPERTIES=false

solves the problem.

**Comment by hengsin** [comment]
should work now, please re-test.
